server:
  port: ${PORT:3001} # Render sets PORT env variable

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/mydatabase}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

app:
  jwt:
    secret: ${JWT_SECRET:CHANGE_ME_TO_A_LONG_RANDOM_SECRET_VALUE_32+_CHARS}
    expirationMs: 86400000

# CORS allowed origin for Vite dev server
cors:
  allowedOrigin: ${CORS_ALLOWED_ORIGIN:http://localhost:5173}
