server:
  port: 3001

spring:
  datasource:
    url: jdbc:postgresql://dpg-d2e3c73uibrs738kmq40-a.oregon-postgres.render.com:5432/minimart_db_8znn
    username: minimart_db_8znn_user
    password: q63WP6VT3CM6jwYOxcxPxLcSTOyMNflM
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

app:
  jwt:
    secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_VALUE_32+_CHARS"
    expirationMs: 86400000

# CORS allowed origin for Vite dev server
cors:
  allowedOrigin: "http://localhost:5173"
