server:
  port: 3001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

app:
  jwt:
    secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_VALUE_32+_CHARS"
    expirationMs: 86400000

# CORS allowed origin for Vite dev server
cors:
  allowedOrigin: "http://localhost:5173"
