server:
  port: ${PORT:3001} # Render sets PORT env variable

spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

app:
  jwt:
    secret: ${JWT_SECRET:CHANGE_ME_TO_A_LONG_RANDOM_SECRET_VALUE_32+_CHARS}
    expirationMs: 86400000

# CORS allowed origin for Vite dev server
cors:
  allowedOrigin: ${CORS_ALLOWED_ORIGIN:https://minimartfrontend.netlify.app}
